name: Keep GitHub Streak Alive

on:
  schedule:
    - cron: "0 22 * * *"  # todos los d√≠as a las 22:00 UTC
  workflow_dispatch:

jobs:
  keep-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make empty commit
        run: |
          git config user.name "glyodev"
          git config user.email "admin@glyodev.dev"
          git commit --allow-empty -m "auto-keep-streak"
          git push
