name: Keep GitHub Streak Alive

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  keep-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # importante

      - name: Commit vac√≠o
        run: |
          git config user.name "glyodev"
          git config user.email "admin@glyodev.dev"
          git commit --allow-empty -m "auto-keep-streak"

      - name: Push con PAT
        env:
          PAT: ${{ secrets.PAT_GLYO }}
        run: |
          git push https://x-access-token:${PAT}@github.com/glyodev/glyodev.git HEAD:main
